spring:
  application:
    name: cliente-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

mensaje:
  texto: Configuración obtenida desde Config Server para Cliente Service

# 🛡️ RESILIENCE4J EN LA NUBE PARA CLIENTES
resilience4j:
  circuitbreaker:
    instances:
      pedidoService: # Debe coincidir con el 'name' de la anotación en PedidoCircuitService
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
