spring:
  application:
    name: pedido-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

mensaje:
  texto: Configuración obtenida desde Config Server para Pedido Service
